// Frontend/src/lib/components/VideoEmbed.svelte
<script lang="ts">
	let { url, title = 'Video Player' }: { url: string; title?: string } = $props();

	// Basic helper to convert standard youtube urls to embed ones
	function getEmbedUrl(source: string) {
		if (source.includes('youtube.com/watch?v=')) {
			return source.replace('watch?v=', 'embed/');
		}
		if (source.includes('youtu.be/')) {
			return source.replace('youtu.be/', 'youtube.com/embed/');
		}
		return source;
	}

	let embedUrl = $derived(getEmbedUrl(url));
</script>

<div
	class="relative aspect-16/9 w-full overflow-hidden rounded-xl shadow-xl ring-1 ring-slate-900/5 dark:ring-slate-100/10"
>
	<iframe
		src={embedUrl}
		{title}
		class="absolute top-0 left-0 h-full w-full border-0"
		allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
		allowfullscreen
	></iframe>
</div>

// FrontendNextJs/src/lib/components/VideoEmbed/VideoEmbed.tsx
interface Props {
  url: string;
  title?: string;
}

// Basic helper to convert standard youtube urls to embed ones
function getEmbedUrl(source: string): string {
  if (source.includes('youtube.com/watch?v=')) {
    return source.replace('watch?v=', 'embed/');
  }
  if (source.includes('youtu.be/')) {
    return source.replace('youtu.be/', 'youtube.com/embed/');
  }
  return source;
}

export default function VideoEmbed({ url, title = 'Video Player' }: Props) {
  const embedUrl = getEmbedUrl(url);

  return (
    <div className="overflow-hidden rounded-2xl ring-1 ring-zinc-200 dark:ring-zinc-800">
      <div className="relative aspect-video w-full bg-zinc-100 dark:bg-zinc-900">
        <iframe
          src={embedUrl}
          title={title}
          className="absolute inset-0 h-full w-full border-0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      </div>
    </div>
  );
}
