// Frontend/src/lib/components/BlockList.svelte
<script lang="ts">
	import type { components } from '$lib/types/umbraco';
	import { componentMap } from '../utils/componentMap';

	let { items = [] }: { items: components['schemas']['ApiBlockListModel']['items'] } = $props();
</script>

<div class="flex flex-col space-y-12">
	{#each items as item}
		{@const SvelteComp = componentMap[item.content.contentType]}
		{@const settings = item.settings as any}
		{@const isConstrained = settings?.properties?.constrainToContentColumn !== null}
		{#if SvelteComp}
			<section class={isConstrained ? 'container mx-auto' : ''}>
				<!-- Dynamically render the mapped component, passing all Umbraco properties as Svelte props -->
				<SvelteComp {...item.content.properties} />
			</section>
		{:else}
			<div
				class="rounded bg-yellow-100 p-4 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300"
			>
				Warning: Unrecognized block component "{item.content.contentType}"
			</div>
		{/if}
	{/each}
</div>

// FrontendNextJs/src/lib/components/BlockList.tsx
import type { components } from '@/lib/types/umbraco';
import { componentMap } from '@/lib/utils/componentMap';

interface BlockListProps {
  items: components['schemas']['ApiBlockListModel']['items'];
}

export default function BlockList({ items = [] }: BlockListProps) {
  return (
    <div className="flex flex-col space-y-12">
      {items.map((item, index) => {
        const BlockComponent = componentMap[item.content.contentType];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const settings = item.settings as any;
        const isConstrained = settings?.properties?.constrainToContentColumn !== null;

        if (BlockComponent) {
          return (
            <section key={index} className={isConstrained ? 'container mx-auto' : ''}>
              <BlockComponent {...item.content.properties} />
            </section>
          );
        }

        return (
          <div
            key={index}
            className="rounded bg-yellow-100 p-4 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300"
          >
            Warning: Unrecognized block component &quot;{item.content.contentType}&quot;
          </div>
        );
      })}
    </div>
  );
}
