// FrontendNextJs/src/lib/components/ButtonLink/ButtonLink.tsx
import {
  type ButtonVariant,
  type ButtonSize,
  buttonBaseClasses,
  getButtonVariantClasses,
  getButtonSizeClasses,
} from '@/lib/components/Button/button-styles';

interface Props {
  href: string;
  target?: string;
  variant?: ButtonVariant;
  size?: ButtonSize;
  className?: string;
  label?: string;
  showArrow?: boolean;
}

export default function ButtonLink({
  href,
  target = '_self',
  variant = 'primary',
  size = 'md',
  className = '',
  label = '',
  showArrow = false,
}: Props) {
  const variantClasses = getButtonVariantClasses(variant);
  const sizeClasses = getButtonSizeClasses(size);

  return (
    <a
      href={href}
      target={target}
      className={`group ${buttonBaseClasses} ${variantClasses} ${sizeClasses} ${className}`.trim()}
    >
      {label}
      {showArrow && (
        <span className="transition-transform group-hover:translate-x-1" aria-hidden="true">
          →
        </span>
      )}
    </a>
  );
}

// Frontend/src/lib/components/ButtonLink/ButtonLink.svelte
<script lang="ts">
	import {
		type ButtonVariant,
		type ButtonSize,
		buttonBaseClasses,
		getButtonVariantClasses,
		getButtonSizeClasses
	} from '../Button/button-styles';

	interface Props {
		href: string;
		target?: string;
		variant?: ButtonVariant;
		size?: ButtonSize;
		class?: string;
		label?: string;
		showArrow?: boolean;
	}

	let {
		href,
		target = '_self',
		variant = 'primary',
		size = 'md',
		class: className = '',
		label = '',
		showArrow = false
	}: Props = $props();

	let variantClasses = $derived(getButtonVariantClasses(variant));
	let sizeClasses = $derived(getButtonSizeClasses(size));
</script>

<a {href} {target} class="group {buttonBaseClasses} {variantClasses} {sizeClasses} {className}">
	{label}
	{#if showArrow}
		<span class="transition-transform group-hover:translate-x-1" aria-hidden="true">→</span>
	{/if}
</a>
